# python TauTagAndProbe/python/compareTurnOn.py --input-a ZprimeToTauTau_M4000_Run3.root --input-b ZprimeToTauTau_M4000_Run2.root --pattern 'HLT_IsoMu24_eta2p1_MediumChargedIsoPFTauHPS35_Trk1_eta2p1_Reg_CrossL1_v' --selection gen --output output/ZprimeToTauTau_M4000_vs_VBFHToTauTau_M125_ditau.root --labels ZprimeToTauTau_M4000_Run3,ZprimeToTauTau_M4000_Run2 --var-a tau_gen_vis_pt --var-b tau_gen_vis_eta --pTT 35 --ch tt --ext True

python TauTagAndProbe/python/compareTurnOn.py --input-a ZprimeToTauTau_M4000_Run3.root --input-b ZprimeToTauTau_M4000_Run2.root --pattern 'HLT_IsoMu20_eta2p1_LooseChargedIsoPFTauHPS27_eta2p1_CrossL1_v' --selection gen --output output/ZprimeToTauTau_M4000_vs_VBFHToTauTau_M125_ditau.root --labels ZprimeToTauTau_M4000_Run3,ZprimeToTauTau_M4000_Run2 --var-a tau_gen_vis_pt --var-b tau_gen_vis_eta --pTT 29 --ch mt --ext False

python TauTagAndProbe/python/compareTurnOn.py --input-a ZprimeToTauTau_M4000_Run3.root --input-b ZprimeToTauTau_M4000_Run2.root --pattern 'HLT_IsoMu20_eta2p1_LooseChargedIsoPFTauHPS27_eta2p1_CrossL1_v' --selection gen --output output/ZprimeToTauTau_M4000_vs_VBFHToTauTau_M125_ditau.root --labels ZprimeToTauTau_M4000_Run3,ZprimeToTauTau_M4000_Run2 --var-a tau_gen_vis_pt --var-b tau_gen_vis_eta --pTT 29 --ch et --ext False

# python TauTagAndProbe/python/compareTurnOn.py --input-a DYToLL_M50Run3.root --input-b VBF_110X.root --pattern 'HLT_IsoMu24_eta2p1_MediumChargedIsoPFTauHPS35_Trk1_eta2p1_Reg_CrossL1_v' --selection gen --output output/ZPRIMETOTAUTAU_M4000_VS_VBFHTOTAUTAU_M125_DITAU.ROOT --labels DYJetsM50_Run3,VBFHToTauTau_Run2 --var-a tau_gen_vis_pt --var-b tau_gen_vis_eta --pTT 35 --ch tt --ext True

# python TauTagAndProbe/python/compareTurnOn.py --input-a DYToLL_M50Run3.root --input-b VBF_110X.root --pattern 'HLT_IsoMu20_eta2p1_LooseChargedIsoPFTauHPS27_eta2p1_CrossL1_v' --selection gen --output output/ZprimeToTauTau_M4000_vs_VBFHToTauTau_M125_ditau.root --labels DYJetsM50_Run3,VBFHToTauTau_Run2 --var-a tau_gen_vis_pt --var-b tau_gen_vis_eta --pTT 29 --ch mt --ext False

# python TauTagAndProbe/python/compareTurnOn.py --input-a DYToLL_M50Run3.root --input-b VBF_110X.root --pattern 'HLT_IsoMu20_eta2p1_LooseChargedIsoPFTauHPS27_eta2p1_CrossL1_v' --selection gen --output output/ZprimeToTauTau_M4000_vs_VBFHToTauTau_M125_ditau.root --labels DYJetsM50_Run3,VBFHToTauTau_Run2 --var-a tau_gen_vis_pt --var-b tau_gen_vis_eta --pTT 29 --ch et --ext False
